### ISSUE TITLE
完成rosalind.info的前三個程式

### ISSUE THREAD

**Issue by wychung5822** [wychung5822/V2R-biological-information#1]
http://rosalind.info/problems/dna/
http://rosalind.info/problems/rna/
http://rosalind.info/problems/revc/

**Comment by hjtiun852** [comment]
1.Counting DNA Nucleotides 完成
2.Transcribing RNA into DNA 完成
第三題介紹還沒讀，今天就能看完，第一題的介紹看太久，有一小段還看不懂
